# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.0}
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0}
          cache: 'npm'
      - name: npm install and build webpack
        run: |
          node -v
          set SET NODE_OPTIONS=--openssl-legacy-provider
          npm ci 
          # npm audit fix --force
          npm run build

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: npm install and test
      run: |
        npm install
        npm audit fix --force
        npm test -- -u
      env: 
        CI: true
